language: node_js
node_js:
- node
branches:
  only:
  - master
  # npm version tags
  - /^v\d+\.\d+\.\d+$/
cache:
  directories:
  - "$HOME/.npm"
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    tags: true
    repo: kellyselden/git-fixtures
